services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME:
      MONGO_INITDB_ROOT_PASSWORD:
      MONGO_INITDB_DATABASE: fase4entrega
    ports:
      - "27017:27017"
networks:
  app_network:
    driver: bridge

volumes:
  mongodb_data:
